---
- name: Debug - Get Kubernetes nodes info
  command: kubectl get nodes -o json
  register: kubectl_get_nodes_output
  changed_when: false
  failed_when: false

- name: Debug - Print Kubernetes nodes info
  debug:
    var: kubectl_get_nodes_output.stdout

- name: Create monitoring namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Deploy Prometheus
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/prometheus-deployment.yml"
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Deploy Grafana
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/grafana-deployment.yml"
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Get Prometheus deployment info
  command: kubectl get deployment prometheus-deployment -n monitoring -o json
  register: prometheus_deployment_info
  changed_when: false
  failed_when: false
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Print Prometheus deployment info
  debug:
    var: prometheus_deployment_info.stdout

- name: Wait for Prometheus deployment to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    name: prometheus-deployment
    namespace: monitoring
    wait: yes
    wait_condition: available
    wait_timeout: 60
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Wait for Grafana deployment to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    name: grafana-deployment
    namespace: monitoring
    wait: yes
    wait_condition: available
    wait_timeout: 60
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Get Prometheus pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=prometheus
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"
  register: prometheus_pods

- name: Fail if Prometheus pods are not running
  fail:
    msg: "Prometheus pods are not running"
  when: prometheus_pods.resources | length == 0 or prometheus_pods.resources[0].status.phase != 'Running'

- name: Get Grafana pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=grafana
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"
  register: grafana_pods

- name: Fail if Grafana pods are not running
  fail:
    msg: "Grafana pods are not running"
  when: grafana_pods.resources | length == 0 or grafana_pods.resources[0].status.phase != 'Running'