---
- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Reload sysctl
  command: sysctl --system



- name: Find and remove old Docker repository files
  find:
    paths: /etc/apt/sources.list.d
    patterns: "docker*.list"
  register: files_to_delete

- name: Remove old Docker repository files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Find and remove old Docker GPG key files
  find:
    paths: /etc/apt/keyrings
    patterns: "docker*.asc"
  register: gpg_files_to_delete

- name: Remove old Docker GPG key files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ gpg_files_to_delete.files }}"

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add Docker apt repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

- name: List files in sources.list.d
  command: ls -la /etc/apt/sources.list.d/
  register: sources_list_d

- name: Print sources.list.d
  debug:
    var: sources_list_d.stdout_lines

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Create docker daemon config directory
  file:
    path: /etc/docker
    state: directory

- name: Configure Docker to use systemd cgroup driver
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip

- name: Install Kubernetes Python client
  pip:
    name: kubernetes
    executable: pip3

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config if it doesn't exist
  shell: containerd config default | sudo tee /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Configure containerd to use systemd cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup = false'
    line: '            SystemdCgroup = true'
    state: present

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Add Kubernetes GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
    state: present

- name: Install Kubernetes packages
  apt:
    name: "{{ item }}={{ k8s_version }}-*"
    state: present
    allow_downgrade: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started
