apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sdv-local-storage
  resources:
    requests:
      storage: 1Gi
