---
- name: Deploy sdv-frontend
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/sdv-frontend-deployment.yml"
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Get sdv-frontend deployment info
  command: kubectl get deployment sdv-frontend-deployment -n sdv -o json
  register: sdv_frontend_deployment_info
  changed_when: false
  failed_when: false
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Print sdv-frontend deployment info
  debug:
    var: sdv_frontend_deployment_info.stdout

- name: Initialize sdv_frontend_pods variable
  set_fact:
    sdv_frontend_pods: {}

- name: Wait for sdv-frontend pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: sdv
    label_selectors:
      - app=sdv-frontend
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"
  register: sdv_frontend_pods

- name: Debug - sdv-frontend pods info
  debug:
    var: sdv_frontend_pods

- name: Pause for 60 seconds to allow sdv-frontend pod to stabilize
  pause:
    seconds: 60

- name: Fail if sdv-frontend pods are not running
  fail:
    msg: "sdv-frontend pods are not running"
  when: sdv_frontend_pods.resources | default([]) | length == 0 or sdv_frontend_pods.resources[0].status.phase != 'Running' or not sdv_frontend_pods.resources[0].status.containerStatuses[0].ready
