---
- name: Deploy sdv-frontend
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/sdv-frontend-deployment.yml"
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Get sdv-frontend deployment info
  command: kubectl get deployment sdv-frontend-deployment -n sdv -o json
  register: sdv_frontend_deployment_info
  changed_when: false
  failed_when: false
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Print sdv-frontend deployment info
  debug:
    var: sdv_frontend_deployment_info.stdout

- name: Wait for sdv-frontend pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: sdv
    label_selectors:
      - app=sdv-frontend
    wait: yes
    wait_condition: Ready
    wait_timeout: 120
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - sdv-frontend pods info
  debug:
    var: sdv_frontend_pods
