---
- hosts: all
  become: yes
  tasks:
    - name: Reset Kubernetes cluster
      command: kubeadm reset -f
      ignore_errors: yes

    - name: Remove Kubernetes packages
      apt:
        name: "{{ item }}"
        state: absent
        autoremove: yes
        purge: yes
        allow_change_held_packages: yes
      loop:
        - kubeadm
        - kubectl
        - kubelet

    - name: Remove containerd package
      apt:
        name: containerd
        state: absent
        autoremove: yes
        purge: yes

    - name: Flush iptables rules
      shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

    - name: Remove directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - "$HOME/.kube"
        - /var/lib/etcd
        - /etc/containerd
        - /etc/cni