---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --kubernetes-version {{ k8s_version }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: Setup kubeconfig for user
  file:
    path: "$HOME/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'

- name: Copy admin.conf to root's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    remote_src: yes
    owner: root
    group: root
    mode: '0600'

- name: Verify kubeconfig file permissions and ownership
  stat:
    path: "{{ ansible_user_dir }}/.kube/config"
  register: kubeconfig_stat

- name: Debug - Kubeconfig file stats
  debug:
    var: kubeconfig_stat

- name: Debug - Kubeconfig file content
  command: cat "{{ ansible_user_dir }}/.kube/config"
  register: kubeconfig_content
  changed_when: false
  no_log: true

- name: Debug - Print Kubeconfig content
  debug:
    var: kubeconfig_content.stdout

- name: Install Calico CNI
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  args:
    creates: /etc/cni/net.d/calico-kubeconfig

- name: Get Kubernetes node name
  command: kubectl get nodes -o jsonpath='{.items[0].metadata.name}'
  register: k8s_node_name
  changed_when: false
  environment:
    KUBECONFIG: "/root/.kube/config"

- name: Check if control-plane taint exists on the node
  command: kubectl get nodes {{ k8s_node_name.stdout }} -o jsonpath='{.spec.taints}'
  register: node_taints_check
  changed_when: false
  failed_when: false
  environment:
    KUBECONFIG: "/root/.kube/config"

- name: Untaint control-plane node for single node cluster
  command: kubectl taint nodes {{ k8s_node_name.stdout }} node-role.kubernetes.io/control-plane:NoSchedule-
  environment:
    KUBECONFIG: "/root/.kube/config"
  when: node_taints_check.stdout is search('node-role.kubernetes.io/control-plane:NoSchedule')
