---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ kube_api_ip }} --kubernetes-version {{ k8s_version }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: Setup kubeconfig for user
  file:
    path: "$HOME/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'

- name: Copy admin.conf to root's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    remote_src: yes
    owner: root
    group: root
    mode: '0600'

- name: Verify kubeconfig file permissions and ownership
  stat:
    path: "{{ ansible_user_dir }}/.kube/config"
  register: kubeconfig_stat

- name: Debug - Kubeconfig file stats
  debug:
    var: kubeconfig_stat

- name: Debug - Kubeconfig file content
  command: cat "{{ ansible_user_dir }}/.kube/config"
  register: kubeconfig_content
  changed_when: false
  no_log: true

- name: Debug - Print Kubeconfig content
  debug:
    var: kubeconfig_content.stdout

- name: Download Calico CNI manifest
  ansible.builtin.get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: '0644'

- name: Configure Calico CNI pod network CIDR
  ansible.builtin.replace:
    path: /tmp/calico.yaml
    regexp: '            - name: CALICO_IPV4POOL_CIDR\n              value: "192.168.0.0/16"'
    replace: '            - name: CALICO_IPV4POOL_CIDR\n              value: "10.244.0.0/16"'

- name: Install Calico CNI
  command: kubectl apply -f /tmp/calico.yaml
  args:
    creates: /etc/cni/net.d/calico-kubeconfig

- name: Get Kubernetes node name
  command: kubectl get nodes -o jsonpath='{.items[0].metadata.name}'
  register: k8s_node_name
  changed_when: false
  environment:
    KUBECONFIG: "/root/.kube/config"

- name: Untaint control-plane node for single node cluster
  command: kubectl taint nodes {{ k8s_node_name.stdout }} node-role.kubernetes.io/control-plane:NoSchedule-
  environment:
    KUBECONFIG: "/root/.kube/config"
  register: taint_removal_result
  failed_when: "taint_removal_result.rc != 0 and 'not found' not in taint_removal_result.stderr"
  changed_when: "taint_removal_result.rc == 0"
