apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: sdv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sdv-local-storage
  resources:
    requests:
      storage: 1Gi
