---
- name: Create MinIO storage directory
  file:
    path: /mnt/minio-storage/
    state: directory
    mode: '0777'

- name: Create minio namespace
  kubernetes.core.k8s:
    name: minio
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Deploy MinIO
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/minio-deployment.yml"
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Get MinIO deployment info
  command: kubectl get deployment minio-deployment -n minio -o json
  register: minio_deployment_info
  changed_when: false
  failed_when: false
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Debug - Print MinIO deployment info
  debug:
    var: minio_deployment_info.stdout

- name: Wait for MinIO deployment to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    name: minio-deployment
    namespace: minio
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"

- name: Get MinIO pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: minio
    label_selectors:
      - app=minio
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"
  register: minio_pods

- name: Fail if MinIO pods are not running
  fail:
    msg: "MinIO pods are not running"
  when: minio_pods.resources | length == 0 or minio_pods.resources[0].status.phase != 'Running'
